### PR TITLE
dht variance contributions table

### PR DESCRIPTION
**Pull request by dill**
Adding a variance contributions output table

### CODE REVIEW

**Comment by dill** [comment]
Resolves (at least partially) issues #52, #63 and #70.

**Comment by dill** [comment]
Possible additional changes per chat with @lenthomas:

- display both expected and observed group size and standard error **on request**
- update documentation to let people know what's happening in this table
- remove "clusters" results, only report individuals by default? (Just changing the `print` method.)
- by default print variance contributions

So by default users will see table for individuals estimates adn the variance contributions table.

**Comment by dill** [comment]
The above comment is now addressed minus the general comments needed in the documentation. See `?print.dht` for new options.

**Comment by LHMarshall** [comment]
See issue #76

**Comment by LHMarshall** [comment]
I have now moved these changes to dht-var-tables-LM I will merge them in to master from there

**Pull request closed without merging**
